"""DocumentationService — assembles markdown docs from persisted analysis.

The LLM-augmented version (Phase 4) wraps this with prose generation. v1 of
each endpoint returns a fact-grounded markdown rendering derived from the
database — useful even when Ollama is unreachable.
"""
from __future__ import annotations

import uuid
from datetime import UTC, datetime

from app.core.exceptions import (
    AnalysisNotReadyError,
    RepositoryNotFoundError,
)
from app.models.repository import RepositoryStatus
from app.repositories.dependency_repository import DependencyRepository
from app.repositories.metric_repository import MetricRepository
from app.repositories.repository_repository import RepositoryRepository
from app.repositories.source_file_repository import SourceFileRepository
from app.schemas.documentation import (
    DocumentationRequest,
    DocumentationResponse,
    DocumentKind,
)


class DocumentationService:
    def __init__(
        self,
        repository_repo: RepositoryRepository,
        file_repo: SourceFileRepository,
        dep_repo: DependencyRepository,
        metric_repo: MetricRepository,
    ) -> None:
        self._repos = repository_repo
        self._files = file_repo
        self._deps = dep_repo
        self._metrics = metric_repo

    async def generate(
        self,
        repository_id: uuid.UUID,
        payload: DocumentationRequest,
    ) -> DocumentationResponse:
        repo = await self._repos.get(repository_id)
        if repo is None:
            raise RepositoryNotFoundError(f"Repository {repository_id} not found")
        if repo.status != RepositoryStatus.READY:
            raise AnalysisNotReadyError(
                f"Repository status is {repo.status.value}; analysis not ready"
            )

        languages = await self._files.language_breakdown(repository_id)
        top_complex = await self._metrics.top_complex(repository_id, limit=10)
        averages = await self._metrics.averages(repository_id)

        renderers: dict[DocumentKind, callable] = {  # type: ignore[type-arg]
            "readme": _render_readme,
            "architecture": _render_architecture,
            "api": _render_api,
            "onboarding": _render_onboarding,
            "technical_design": _render_tech_design,
            "summary": _render_summary,
        }
        renderer = renderers[payload.kind]
        markdown = renderer(repo, languages, top_complex, averages)

        return DocumentationResponse(
            repository_id=repository_id,
            kind=payload.kind,
            content_markdown=markdown,
            generated_at=datetime.now(UTC).isoformat(),
        )


# ---------------------------------------------------------------------------
# Renderers (pure functions of analysis facts — no LLM in v1)
# ---------------------------------------------------------------------------
def _render_readme(repo, languages, top_complex, averages):
    lang_lines = "\n".join(
        f"- **{lang}** — {count} files" for lang, count in sorted(languages.items())
    )
    return f"""# {repo.owner}/{repo.name}

> Auto-generated by CodeSensei

## Overview
- Repository: <{repo.url}>
- Branch: `{repo.branch or repo.default_branch or 'main'}`
- Files analyzed: {repo.file_count}
- Total lines: {repo.total_lines:,}

## Languages
{lang_lines or '- (no recognised languages)'}

## Complexity at a glance
- Average cyclomatic complexity: {averages['cyclomatic']:.2f}
- Average cognitive complexity: {averages['cognitive']:.2f}
- Median lines of code per file: {averages['loc_median']:.0f}
"""


def _render_architecture(repo, languages, top_complex, averages):
    return f"""# Architecture — {repo.owner}/{repo.name}

The repository spans **{repo.file_count} files** across **{len(languages)} languages**.
Use the dependency-graph endpoint for a navigable view and the impact-analysis
endpoint to assess change risk.
"""


def _render_api(repo, languages, top_complex, averages):
    return f"""# API Inventory — {repo.owner}/{repo.name}

API surface enumeration requires per-language route detection (see Phase 4).
The analysis run has indexed {repo.file_count} files.
"""


def _render_onboarding(repo, languages, top_complex, averages):
    top_lines = "\n".join(
        f"{idx + 1}. `{file.path}` — cyclomatic {metric.cyclomatic}"
        for idx, (metric, file) in enumerate(top_complex[:5])
    )
    return f"""# Onboarding Guide — {repo.owner}/{repo.name}

Welcome. Here is a 30-minute orientation:

1. Clone <{repo.url}> and check out `{repo.branch or repo.default_branch or 'main'}`.
2. Start with the dependency graph endpoint to see how files connect.
3. Read these high-complexity files first to absorb the trickiest logic:

{top_lines or '(no complexity data yet — re-run analysis)'}
"""


def _render_tech_design(repo, languages, top_complex, averages):
    return f"""# Technical Design — {repo.owner}/{repo.name}

(Auto-generated outline; LLM-enhanced narrative lands in Phase 4.)

## Languages
{', '.join(sorted(languages.keys())) or 'unknown'}

## Hot files (by cyclomatic complexity)
{chr(10).join(f'- {file.path}: {metric.cyclomatic}' for metric, file in top_complex[:10]) or '(no metrics)'}
"""


def _render_summary(repo, languages, top_complex, averages):
    return (
        f"# Summary\n\n"
        f"{repo.owner}/{repo.name} contains {repo.file_count} files and "
        f"{repo.total_lines:,} lines across {len(languages)} languages.\n"
    )
